/**
 * App configuration. Read from `globalThis.window.__PAY_CONFIG__` which is
 * set by public/config.js (generated by local-dev/up.sh in dev, by the
 * deploy workflow in production).
 *
 * No silent fallback to a hardcoded URL: a missing/incomplete config means
 * the app cannot talk to the platform safely, so we fail fast on first
 * access rather than silently pointing the production deploy at testnet.
 *
 * Reads are lazy so this module can be imported in non-browser contexts
 * (unit tests, build tools) without throwing — the throw only happens on
 * the first call to a getter.
 */

export interface PayConfig {
  environment?: string;
  stellarNetwork?: StellarNetwork;
  payPlatformUrl?: string;
  rpcUrl?: string;
  allowlist?: string[];
}

export type StellarNetwork = "testnet" | "mainnet" | "standalone";

interface ResolvedConfig {
  environment: string;
  stellarNetwork: StellarNetwork;
  payPlatformUrl: string;
  rpcUrl: string;
}

let cached: ResolvedConfig | null = null;

function readWindowConfig(): PayConfig | undefined {
  // Read via globalThis.window so this works in both browser bundles and
  // Deno tests (which can stub `globalThis.window` to control the value).
  // deno-lint-ignore no-explicit-any
  const w = (globalThis as any).window;
  return w?.__PAY_CONFIG__;
}

function readConfig(): ResolvedConfig {
  if (cached) return cached;
  const cfg = readWindowConfig();
  if (!cfg?.payPlatformUrl) {
    throw new Error(
      "Moonlight Pay misconfigured: window.__PAY_CONFIG__.payPlatformUrl is required. " +
        "Make sure public/config.js is loaded before app.js and defines payPlatformUrl.",
    );
  }
  cached = {
    environment: cfg.environment ?? "production",
    stellarNetwork: cfg.stellarNetwork ?? "testnet",
    payPlatformUrl: cfg.payPlatformUrl,
    rpcUrl: cfg.rpcUrl ?? "https://soroban-testnet.stellar.org",
  };
  return cached;
}

/** Test hook — clears the memoized config so a new window value is re-read. */
export function __resetConfigForTests(): void {
  cached = null;
}

export function getEnvironment(): string {
  return readConfig().environment;
}

export function isProduction(): boolean {
  return getEnvironment() === "production";
}

export function getStellarNetwork(): StellarNetwork {
  return readConfig().stellarNetwork;
}

export function getPayPlatformUrl(): string {
  return readConfig().payPlatformUrl;
}

export function getRpcUrl(): string {
  return readConfig().rpcUrl;
}

export function getNetworkPassphrase(): string {
  switch (getStellarNetwork()) {
    case "mainnet":
      return "Public Global Stellar Network ; September 2015";
    case "standalone":
      return "Standalone Network ; February 2017";
    default:
      return "Test SDF Network ; September 2015";
  }
}

export function isAllowed(address: string): boolean {
  const cfg = readWindowConfig();
  const list = cfg?.allowlist ?? [];
  return list.includes("*") || list.includes(address);
}
