name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build (dev)
        working-directory: apps/self
        run: deno task build
      - name: Build (production)
        working-directory: apps/self
        run: deno task build -- --production

  build-custodial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build (dev)
        working-directory: apps/custodial
        run: deno task build
      - name: Build (production)
        working-directory: apps/custodial
        run: deno task build -- --production
